vim.g.mapleader = " "
vim.keymap.set("n", "j", "gj")
vim.keymap.set("n", "<Leader>s", function()
	vim.opt.spell = not vim.opt.spell:get()
end)
--vim.keymap.set("n", "<leader>ca", ":CodeActionMenu<CR>", {silent=true})
--vim.keymap.set("i", "<C-l>", "copilot#Accept()", { silent=true, expr=true, nowait=true, script=true })
vim.cmd("imap <script><silent><nowait><expr> <C-l> copilot#Accept()")
--vim.keymap.set("i", "<M-j>", "copilot#Next()", { silent=true, expr=true, nowait=true, script=true })
--vim.keymap.set("i", "<M-k>", "copilot#Previous()", { silent=true, expr=true, nowait=true, script=true })
vim.keymap.set("n", "'", "`")
vim.keymap.set("n", "`", "'")
